###############################################################################
###########################    BUILD STAGE     ################################
###############################################################################

# syntax=docker/dockerfile:experimental
FROM eflows/ucis4eq/base:latest AS build

# Install dependencies
RUN pip install --upgrade setuptools; pip install numpy flask pymongo pyyaml requests; pip install obspy webdavclient3

# Prepare the service to run
RUN mkdir -p /opt/services;
    
# Expose the Flask application port
EXPOSE 5003

# Obtain the SalvusService App
ADD code/services/simulatorService.py /opt/services/simulatorService.py

# Prepare an script able to start the slip-generator service
RUN echo "python /opt/services/simulatorService.py" >> /opt/services/start.sh
 
# Start a shell
ENTRYPOINT ["/bin/bash", "/root/scripts/launcher.sh"]
